<a href="https://colab.research.google.com/github/pablex72/numpy-panda/blob/main/appliying_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
#np.arange (Start,Ens,Steps) → es como el list( range(0,10)) pero como arrange
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [13]:
# np.linspace(Start, End, evenly spaced samples over interval Space and End)
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [14]:
#matriz identidad
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# np.random.rand(Filas, Columnas, mas dimensiones ) 
np.random.rand()

0.9000653226323352

In [16]:
np.random.rand(2,2)

array([[0.09971733, 0.6053845 ],
       [0.62020579, 0.11715202]])

In [17]:
np.random.randint(1,15)

3

In [18]:
##valores enteros de 1 a 100 con una estructura de 10x10

np.random.randint(1,100,(10,10))

array([[74, 15, 67, 18, 15, 90, 37, 62, 79, 72],
       [ 8, 93, 31, 88, 60, 86, 92, 21, 49, 56],
       [50, 13, 27, 47, 54,  5, 52, 97, 20, 35],
       [85, 75, 96, 32, 64, 54, 67, 47, 90, 16],
       [35, 46, 29, 89, 71, 78, 32, 12, 26, 11],
       [64, 41,  4, 40, 46, 46, 99, 52, 68, 38],
       [72, 71, 82, 31, 97, 27, 60, 24, 37, 91],
       [16, 62, 84, 45,  1, 59, 46, 73, 56, 37],
       [91, 79, 53, 80, 75, 23,  4,  5, 50, 46],
       [16, 29, 11, 91, 75, 13, 19, 45, 97, 52]])