<a href="https://colab.research.google.com/github/pablex72/numpy-panda/blob/main/Conditionals_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [5]:
indicesCondicionales = arr > 5
indicesCondicionales

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
arr[indicesCondicionales]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [7]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [9]:
arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [12]:
#Operations
lista = [1,2]
lista


[1, 2]

In [13]:
lista * 2

[1, 2, 1, 2]

In [14]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [20]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
#producto punto
matriz3 = matriz2.T
np.matmul(matriz,matriz3)

array([[ 30,  80],
       [ 80, 255]])

In [23]:
#PRODUCTO PUNTO con matriz
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])