<a href="https://colab.research.google.com/github/pablex72/numpy-panda/blob/main/Principles_functions_Numpy_Copy_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)

In [3]:
matriz = arr.reshape(2,5)
matriz

array([[ 2, 15, 19, 10,  4],
       [11, 11, 14,  5,  6]])

In [4]:
arr

array([ 2, 15, 19, 10,  4, 11, 11, 14,  5,  6])

In [7]:
#por matriz por ejes, filas y columnas -> filas
matriz.max(1)

array([19, 14])

In [8]:
#por matriz por ejes, filas y columnas -> columnas
matriz.max(0)

array([11, 15, 19, 10,  6])

In [11]:
#show the position of maximun
arr.argmax()

2

In [13]:
arr.argmax(0)

2

In [15]:
#de un pico al otro pico
arr.ptp()

17

In [17]:
matriz.ptp(0)

array([9, 4, 5, 5, 2])

In [20]:
#percentile, cual es el valor que se encuentra en la mitad con 50 --> 0 a 100 : min to max-> 50 sera la mitad --> la media entre los dos valores de la mitad
np.percentile(arr,50)

10.5

In [21]:
np.median(arr)

10.5

In [22]:
#mediana es el valor donde se ubica la mitad = percentile 50
np.median(matriz,1)

array([10., 11.])

In [23]:
np.std(arr)

5.139066063011839

In [24]:
#varianza = std^2
np.var(arr)

26.410000000000004

In [25]:
#promedio suma /n
np.mean(arr)

9.7

In [27]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
a
b

array([5, 6])

In [28]:
np.concatenate((a,b),axis=0)

ValueError: ignored

In [29]:
a.ndim

2

In [30]:
b = np.expand_dims(b,axis=0)

In [31]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [34]:
b.T

array([[5],
       [6]])

In [35]:
##COPY
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# sigue haciendo referencia a arr a ese objeto en memoria
#cualquier cambio que ocurra en trozoArr afectara al padre arr
trozoArr = arr[0:6]
trozoArr

In [38]:
trozoArr[:] = 0
trozoArr

array([0, 0, 0, 0, 0, 0])

In [39]:
#esto se enmienda con COPY --> asi se tendra dos distintos
arr_copy = arr.copy()

In [40]:
arr_copy[:] = 100

In [41]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [42]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])