<a href="https://colab.research.google.com/github/pablex72/numpy-panda/blob/main/Using_shape_and_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Shape me indica la forma del arreglo--> indica con que estructura estamos trabajando -- > dice cuantas filas y columns o dimensiones tengo
#Reshape transforma el arreglo mientras se mantengan los elementos. --> cambia la forma de un array
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,2))

In [3]:
arr.shape

(3, 2)

In [4]:
arr

array([[3, 4],
       [6, 2],
       [8, 1]])

In [5]:
arr.reshape(1,6)

array([[3, 4, 6, 2, 8, 1]])

In [6]:
arr.reshape(2,3)

array([[3, 4, 6],
       [2, 8, 1]])

In [7]:
np.reshape(arr,(1,6))

array([[3, 4, 6, 2, 8, 1]])

In [8]:
arr

array([[3, 4],
       [6, 2],
       [8, 1]])

In [9]:
#lenguaje C y o Fortran o A= aleatorio -->usar C
np.reshape(arr,(2,3),'C')

array([[3, 4, 6],
       [2, 8, 1]])

In [ ]:
np.reshape(arr,(2,3),'F')

In [10]:
array_original = np.random.randint(0,10, (3,3))
array_original

array([[7, 6, 1],
       [5, 8, 3],
       [1, 8, 2]])

In [11]:
array_original.reshape(1,9)

array([[7, 6, 1, 5, 8, 3, 1, 8, 2]])